
title: OonDev
email: leos9877@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

author: Lucas Eduardo de Oliveira Santos
github_username: LucasSantus
url: https://www.abhinavsaxena.com/moonwalk

baseurl: "/"

permalink: /:title

favicon: "./logo.png"

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
